EHaliSaha/EHaliSaha/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EHaliSaha.Controllers
{
    public class GalleryController : Controller
    {
        // GET: Gallery
        public ActionResult Index()
        {
            return View();
        }
    }
}

EHaliSaha/EHaliSaha/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@ViewBag.Title - EHalıSaha</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

        <!-- Bootstrap -->
        <link rel="stylesheet" href="/Content/css/font-awesome.min.css">
        <link rel="stylesheet" href="/Content/css/animate.css">
        <link href="/Content/css/animate.min.css" rel="stylesheet">
        <link href="/Content/css/style.css" rel="stylesheet" />
       
    </head>

</head>
<body>
    <header id="header">
        <nav class="navbar navbar-default navbar-static-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                       <h5>G141210057<br />FIRAT ÇELİK</h5>
                    </div>
                </div>
                <div class="navbar-collapse collapse"> @*Buranın İçine Bak*@
                    <div class="menu">
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation">@Html.ActionLink("AnaSayfa", "Index", "Home")</li>
                            <li>@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                            <li>@Html.ActionLink("Resimler", "Index", "Gallery")</li>
                            <li>@Html.ActionLink("İletisim","Contact","Home")</li> 
                            @*<li>@Html.ActionLink("         ", "Index", "Home")</li>
                            <li>@Html.ActionLink("Kayıt Ol", "Register", "Account")</li>
                            <li>@Html.ActionLink("Giriş Yap", "Login", "Account")</li>*@
                            <li>@Html.Partial("_LoginPartial")</li>
                        </ul>
                    </div>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
    </header><!--/header-->

        @RenderBody()

    <footer>
        <div class="container">
            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                <h4>Bize Ulaşın</h4>
                <p>Halısaha Randevuları İçin Bir Tık Kadar Uzağız</p>
                <div class="contact-info">
                    <ul>
                        <li><i class="fa fa-home fa"></i>Kemalpaşa Mahallesi Necip Fazıl Kısakürek Caddesi Adatepe Konutları C Blok Daire 8</li>
                        <li><i class="fa fa-phone fa"></i> +90 533 853 32 23</li>
                        <li><i class="fa fa-envelope fa"></i> celikfirattt@outlook.com</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                <div class="text-center">
                    <h4>Fotoğraf Galerisi</h4>
                    <ul class="sidebar-gallery">
                        <li><a href="#"><img src="~/Content/img/1.png" alt="" /></a></li>
                        <li><a href="#"><img src="~/Content/img/2.png" alt="" /></a></li>
                        <li><a href="#"><img src="~/Content/img/3.png" alt="" /></a></li>
                        <li><a href="#"><img src="~/Content/img/4.png" alt="" /></a></li>
                        <li><a href="#"><img src="~/Content/img/5.png" alt="" /></a></li>
                        <li><a href="#"><img src="~/Content/img/6.png" alt="" /></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">
                <div class="">
                    <h4>Neyi Aramıştınız</h4>
                    <div class="btn-gamp">
                        <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Search">
                    </div>
                    <div class="btn-gamp">
                        <a type="submit" class="btn btn-default">Ara</a>
                    </div>

                </div>
            </div>

        </div>
    </footer>

    <div class="sub-footer">
        <div class="container">
            <div class="social-icon">
                <div class="col-md-4">
                    <ul class="social-network">
                        <li><a href="https://www.facebook.com" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/?lang=tr" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://plus.google.com/   " class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                        @*<li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>*@
                        <li><a href="https://www.youtube.com/" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 col-md-offset-4">
                <div class="copyright">
                    &copy; Day Theme. All Rights Reserved.
                    <div class="credits">
                        <!--
                            All the links in the footer should remain intact.
                            You can delete the links only if you purchased the pro version.
                            Licensing information: https://bootstrapmade.com/license/
                            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Day
                        -->
                        <a href="https://bootstrapmade.com/">Tüm Hakları Saklıdır</a> by <a href="https://bootstrapmade.com/">Fırat Çelik</a>
                    </div>
                </div>
            </div>
        </div>
    </div>



    @Scripts.Render("~/bundles/wow")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="js/wow.min.js"></script>
        <script>wow = new WOW({}).init();</script>*@
    @RenderSection("scripts", required: false)
</body>

</html>