EHaliSaha/EHaliSaha/Areas/Admin/Controllers/KullanicilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EHaliSaha.Areas.Admin.Controllers
{
    [Authorize(Roles = "yonetici")]
    public class KullanicilarController : Controller
    {   
        EHalisahaEntities2 db = new EHalisahaEntities2();
        // GET: Admin/Kullanicilar  
        public ActionResult Index()
        {
            var kullanicilar = db.kullanicilar.OrderBy(x=>x.id).ToList();
            return View(kullanicilar);
        }    
        public ActionResult Add()
        {
            return View();
        }
        public ActionResult AddKullanici(kullanicilar model)
        {
            if (ModelState.IsValid)
            {
                db.kullanicilar.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");    
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.kullanicilar.Find(id);
            //var model = db.kullanicilar.FirstOrDefault(x => x.id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(kullanicilar model)
        {
            if (ModelState.IsValid)
            {
                db.kullanicilar.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var model=db.kullanicilar.Find(id);
            return View(model);
        }
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.kullanicilar.Find(id);
            db.kullanicilar.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

EHaliSaha/EHaliSaha/Areas/Admin/Views/Kullanicilar/Add.cshtml
@model EHaliSaha.kullanicilar

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("AddKullanici", "Kullanicilar",FormMethod.Post,new { @class = "form-horizantal" }))
{
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    Advanced Form validations
                </header> 
                <div class="panel-body">
                    <div class="form">
                        <form class="form-validate form-horizontal " id="register_form" method="get" action="">
                            <div class="form-group ">
                                @Html.LabelFor(m=>m.ad, new {@class= "control-label col-lg-2" })

                                <div class="col-lg-10">
                                    @Html.TextBoxFor(m => m.ad,new {@class = "form-control",placeholder = "Adınızı Giriniz" })
                                    
                                    <br />
                                </div>
                            </div>
                            <div class="form-group ">
                                @Html.LabelFor(m => m.soyad, new { @class = "control-label col-lg-2" })

                                <div class="col-lg-10">
                                    @Html.TextBoxFor(m => m.soyad, new { @class = "form-control", placeholder = "Soyadınızı Giriniz" })

                                    <br />
                                </div>
                            </div>
                            <div class="form-group ">
                                @Html.LabelFor(m => m.yas, new { @class = "control-label col-lg-2" })

                                <div class="col-lg-10">
                                    @Html.TextBoxFor(m => m.yas, new { @class = "form-control", placeholder = "Yaşınızı Giriniz" })

                                    <br />
                                </div>
                            </div>
                            <div class="form-group ">
                                @Html.LabelFor(m => m.tel, new { @class = "control-label col-lg-2" })

                                <div class="col-lg-10">
                                    @Html.TextBoxFor(m => m.tel, new { @class = "form-control", placeholder = "Telefon Giriniz" })

                                    <br />
                                </div>
                            </div>
                            <div class="form-group ">
                                @Html.LabelFor(m => m.halisaha_adi, new { @class = "control-label col-lg-2" })

                                <div class="col-lg-10">
                                    @Html.TextBoxFor(m => m.halisaha_adi, new { @class = "form-control", placeholder = "HalıSaha Seçiniz  " })

                                    <br />
                                </div>
                            </div>
                            <div class="form-group ">
                                @Html.LabelFor(m => m.randevu_tarihi, new { @class = "control-label col-lg-2" })

                                <div class="col-lg-10">
                                    @Html.TextBoxFor(m => m.randevu_tarihi, new { @class = "form-control", placeholder = "Randevu Tarihi Seçiniz" })

                                    <br />
                                </div>
                            </div>
                          
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary" type="submit">Ekle</button>
                                    <button class="btn btn-default" type="button">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>

}

EHaliSaha/EHaliSaha/Areas/Admin/Views/Kullanicilar/Delete.cshtml
@model EHaliSaha.kullanicilar

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>kullanicilar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.yas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.yas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.yetki)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.yetki)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Sil", "DeleteConfirm", new { id = Model.id }) |   |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
    }

EHaliSaha/EHaliSaha/Areas/Admin/Views/Kullanicilar/Edit.cshtml
@model EHaliSaha.kullanicilar

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>kullanicilar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.yas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.yas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.yas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.randevu_tarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.randevu_tarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.randevu_tarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.halisaha_adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.halisaha_adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.halisaha_adi, "", new { @class = "text-danger" })
            </div>
        </div>

      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EHaliSaha/EHaliSaha/Areas/Admin/Views/Kullanicilar/Index.cshtml
@model List<kullanicilar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
               <p align="center">@Html.ActionLink("Kullanıcı Ekle", "Add")</p>
</header>

            <table class="table table-striped table-advance table-hover">
                <tbody>
                    <tr>
                        <th><i class="icon_profile"></i> Ad Soyad</th>
                        <th><i class="icon_calendar"></i> Randevu Tarihi</th>
                        <th><i class="icon_mail_alt"></i> Yaş</th>
                        <th><i class="icon_pin_alt"></i> Halı Saha Adı</th>
                        <th><i class="icon_mobile"></i> Telefon</th>
                        <th><i class="icon_cogs"></i> Action</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ad @item.soyad</td>
                            <td>@item.randevu_tarihi</td>
                            <td>@item.yas</td>
                            <td>@item.halisaha_adi</td>
                            <td>@item.tel</td>
                            <td>
                                <div class="btn-group">
                                    @*@Html.ActionLink("Detaylar", "Details", "Kullanicilar", new { id = item.id },null)*@
                                    @Html.ActionLink("Düzenle", "Edit", "Kullanicilar", new { id = item.id },null)
                                    @Html.ActionLink("Sil", "Delete", "Kullanicilar", new { id = item.id },null)
                                </div>
                            </td>
                        </tr>

                    }
                    
                </tbody>
            </table>
        </section>
    </div>
</div>